[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd react_frontend && npm install"]

[phases.build]
cmds = ["cd react_frontend && npm run build"]

[start]
cmd = "cd react_frontend && ./node_modules/.bin/serve -s dist --listen tcp://0.0.0.0:$PORT"
