[phases.install]
cmds = ["cd backend && dotnet restore"]

[phases.build]
cmds = ["cd backend && dotnet publish -c Release -o out"]

[start]
cmd = "dotnet backend/out/backend.dll"

[start]
cmd = "cd react_frontend && ./node_modules/.bin/serve -s dist --listen tcp://0.0.0.0:$PORT"
