// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RightFitGigs.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RightFitGigs.Models.Advertisement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClickCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FadeDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDismissible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.HasIndex("Placement");

                    b.HasIndex("Platform");

                    b.HasIndex("StartDate");

                    b.HasIndex("Type");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("RightFitGigs.Models.AppMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("MetricType");

                    b.HasIndex("Platform");

                    b.ToTable("AppMetrics");
                });

            modelBuilder.Entity("RightFitGigs.Models.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("RightFitGigs.Models.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Industry");

                    b.HasIndex("Location");

                    b.HasIndex("Name");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = "company-1-tech",
                            CreatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 885, DateTimeKind.Utc).AddTicks(7250),
                            Description = "Leading technology company specializing in mobile and web solutions",
                            Email = "hr@techcorp.com",
                            Industry = "Technology",
                            IsActive = true,
                            Location = "San Francisco",
                            Name = "Tech Corp",
                            Size = "100-500",
                            UpdatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 885, DateTimeKind.Utc).AddTicks(7250),
                            Website = "https://techcorp.com"
                        },
                        new
                        {
                            Id = "company-2-mobile",
                            CreatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 886, DateTimeKind.Utc).AddTicks(1110),
                            Description = "Mobile-first development company",
                            Email = "careers@mobilesolutions.com",
                            Industry = "Technology",
                            IsActive = true,
                            Location = "Remote",
                            Name = "Mobile Solutions",
                            Size = "50-100",
                            UpdatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 886, DateTimeKind.Utc).AddTicks(1110),
                            Website = "https://mobilesolutions.com"
                        },
                        new
                        {
                            Id = "company-3-design",
                            CreatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 886, DateTimeKind.Utc).AddTicks(1130),
                            Description = "Creative design agency for digital products",
                            Email = "jobs@designstudio.com",
                            Industry = "Design",
                            IsActive = true,
                            Location = "New York",
                            Name = "Design Studio",
                            Size = "10-50",
                            UpdatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 886, DateTimeKind.Utc).AddTicks(1130),
                            Website = "https://designstudio.com"
                        });
                });

            modelBuilder.Entity("RightFitGigs.Models.Job", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeasonal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUrgentlyHiring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Location");

                    b.HasIndex("PostedDate");

                    b.HasIndex("Title");

                    b.HasIndex("Type");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = "job-1-flutter",
                            Company = "Tech Corp",
                            CompanyId = "company-1-tech",
                            Description = "Looking for an experienced Flutter developer to join our team.",
                            IsActive = true,
                            IsRemote = false,
                            IsSeasonal = false,
                            IsUrgentlyHiring = false,
                            Location = "Remote",
                            PostedDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salary = "$80k - $120k",
                            Title = "Flutter Developer",
                            Type = "Full-time",
                            UpdatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 887, DateTimeKind.Utc).AddTicks(320)
                        },
                        new
                        {
                            Id = "job-2-ios",
                            Company = "Mobile Solutions",
                            CompanyId = "company-2-mobile",
                            Description = "Native iOS development position with competitive benefits.",
                            IsActive = true,
                            IsRemote = false,
                            IsSeasonal = false,
                            IsUrgentlyHiring = false,
                            Location = "San Francisco",
                            PostedDate = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salary = "$90k - $130k",
                            Title = "iOS Developer",
                            Type = "Full-time",
                            UpdatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 887, DateTimeKind.Utc).AddTicks(5390)
                        },
                        new
                        {
                            Id = "job-3-designer",
                            Company = "Design Studio",
                            CompanyId = "company-3-design",
                            Description = "Creative designer needed for mobile and web applications.",
                            IsActive = true,
                            IsRemote = false,
                            IsSeasonal = false,
                            IsUrgentlyHiring = false,
                            Location = "New York",
                            PostedDate = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salary = "$70k - $100k",
                            Title = "UI/UX Designer",
                            Type = "Contract",
                            UpdatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 887, DateTimeKind.Utc).AddTicks(5400)
                        },
                        new
                        {
                            Id = "job-4-senior-flutter",
                            Company = "Tech Corp",
                            CompanyId = "company-1-tech",
                            Description = "We are looking for an experienced Flutter developer with 5+ years of experience.",
                            IsActive = true,
                            IsRemote = false,
                            IsSeasonal = false,
                            IsUrgentlyHiring = false,
                            Location = "Remote",
                            PostedDate = new DateTime(2026, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salary = "$100k - $140k",
                            Title = "Senior Flutter Developer",
                            Type = "Full-time",
                            UpdatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 887, DateTimeKind.Utc).AddTicks(5410)
                        });
                });

            modelBuilder.Entity("RightFitGigs.Models.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("IsRead");

                    b.HasIndex("JobId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentDate");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RightFitGigs.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsRead");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RightFitGigs.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredExperienceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredJobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredJobType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredLocation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredSalaryRange")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OpenToRemote")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredIndustries")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Location");

                    b.HasIndex("UserType");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "user-1-john",
                            Bio = "Experienced Flutter developer with passion for mobile development",
                            CreatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 887, DateTimeKind.Utc).AddTicks(6980),
                            Email = "john.smith@example.com",
                            FirstName = "John",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Smith",
                            Location = "San Francisco",
                            OpenToRemote = true,
                            PasswordHash = "$2a$11$eXUE2pctmN2lvrGRJfJiTOLfL02cUcjuY2tnsjG./iopZ6GafngO6",
                            Phone = "555-0101",
                            Skills = "Flutter, Dart, iOS, Android, Firebase",
                            Title = "Senior Flutter Developer",
                            UpdatedDate = new DateTime(2026, 2, 16, 22, 34, 20, 887, DateTimeKind.Utc).AddTicks(6980),
                            UserType = "Worker"
                        });
                });

            modelBuilder.Entity("RightFitGigs.Models.Application", b =>
                {
                    b.HasOne("RightFitGigs.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RightFitGigs.Models.User", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("RightFitGigs.Models.Job", b =>
                {
                    b.HasOne("RightFitGigs.Models.Company", "CompanyNavigation")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CompanyNavigation");
                });

            modelBuilder.Entity("RightFitGigs.Models.Message", b =>
                {
                    b.HasOne("RightFitGigs.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RightFitGigs.Models.User", b =>
                {
                    b.HasOne("RightFitGigs.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RightFitGigs.Models.Company", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
